services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: auth

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

